groups:
  - name: detection-engine.alerts
    rules:
      - alert: DetectionEngineDown
        expr: up{job="detection-engine"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Detection Engine is down"
          description: "Detection Engine has been down for more than 1 minute"

      - alert: HighLatency
        expr: histogram_quantile(0.95, detection_latency_seconds_bucket) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High detection latency"
          description: "P95 latency is {{ $value }}s, above 5s threshold"

      - alert: AllModelsDown
        expr: sum(circuit_breaker_state == 1) >= 3
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "All detection models are down"
          description: "All circuit breakers are open - no models available"

      - alert: ModelCircuitBreakerOpen
        expr: circuit_breaker_state == 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Model circuit breaker is open"
          description: "Circuit breaker for {{ $labels.model }} has been open for 2+ minutes"

      - alert: DetectionThroughputLow
        expr: rate(detection_requests_total[5m]) < 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low detection throughput"
          description: "Detection requests rate is {{ $value }}/s, below 0.1/s threshold"

      - alert: MaliciousDetectionSpike
        expr: rate(detection_requests_total{result="malicious"}[5m]) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High volume of malicious detections"
          description: "Malicious detection rate is {{ $value }}/s, possible attack in progress"

      - alert: ModelFailureRate
        expr: (rate(detection_requests_total{result="error"}[5m]) / rate(detection_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High model failure rate"
          description: "Model failure rate is {{ $value | humanizePercentage }}, above 5% threshold"

  - name: api-gateway.alerts
    rules:
      - alert: APIGatewayDown
        expr: up{job="api-gateway"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API Gateway is down"
          description: "API Gateway has been down for more than 1 minute"

      - alert: HighErrorRate
        expr: (rate(api_requests_total{status!~"2.."}[5m]) / rate(api_requests_total[5m])) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API error rate"
          description: "Error rate is {{ $value | humanizePercentage }}, above 1% threshold"

      - alert: CriticalErrorRate
        expr: (rate(api_requests_total{status!~"2.."}[5m]) / rate(api_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical API error rate"
          description: "Error rate is {{ $value | humanizePercentage }}, above 5% threshold"

      - alert: APIGatewayHighLatency
        expr: histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m])) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "API Gateway high latency"
          description: "P95 API latency is {{ $value }}s, above 3s threshold"

      - alert: APIGatewayCriticalLatency
        expr: histogram_quantile(0.95, rate(api_request_duration_seconds_bucket[5m])) > 8
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "API Gateway critical latency"
          description: "P95 API latency is {{ $value }}s, above 8s threshold (SLA violation)"

      - alert: RateLimitAbuseDetected
        expr: increase(rate_limit_blocks_total[1h]) > 1000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Rate limit abuse detected"
          description: "More than 1000 rate limit blocks in the last hour"

  - name: system.alerts
    rules:
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90%"
        # Only active when node exporter is available